openapi: 3.0.0

info:
  title: sakura-village rest api
  version: 1.0.0

components:
  schemas:
    User:
      description: 用户信息
      type: object
      properties:
        id:
          type: integer
          format: int32
        nickname:
          type: string
          maxLength: 32
        avatar:
          type: string
          maxLength: 512

    Tag:
      description: 指示文章特征的标签
      type: object
      required:
        - title
        - id
      properties:
        title:
          type: string
          maxLength: 16
          minLength: 1
        id:
          type: integer
          format: int32

    Article:
      description: 文章，标题无样式，内容为 markdown 格式。
      type: object
      required:
        - id
        - title
        - content
        - brief
        - tags
      properties:
        id:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/User'
        title:
          type: string
          maxLength: 32
        brief:
          type: string
          maxLength: 100
        content:
          type: string
          maxLength: 50000
        tags:
          type: array
          minLength: 1
          maxLength: 10
          items:
            $ref: '#/components/schemas/Tag'
        created_at:
          description: 创建日期，ISO格式 datetime
          type: string
        updated_at:
          description: 更新日期，ISO格式 datetime
          type: string

    ArticleBrief:
      description: 文章简介信息，用于列出文章索引
      type: object
      required:
        - id
        - title
        - brief
        - tags
      properties:
        id:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/User'
        title:
          type: string
          maxLength: 32
        brief:
          type: string
          maxLength: 100
        tags:
          type: array
          minLength: 1
          maxLength: 10
          items:
            $ref: '#/components/schemas/Tag'
        created_at:
          description: 创建日期，ISO格式 datetime
          type: string
        updated_at:
          description: 更新日期，ISO格式 datetime
          type: string

    ArticleIndex:
      description: 文章索引，文章简介的列表，需要分页获取
      type: object
      required:
        - total
        - page
        - size
        - items
      properties:
        total:
          type: integer
          format: int32
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/ArticleBrief'

    ArticleModification:
      type: object
      properties:
        title:
          type: string
          maxLength: 32
        brief:
          type: string
          maxLength: 100
        content:
          type: string
          maxLength: 50000
        tags:
          type: array
          minLength: 1
          maxLength: 10
          items:
            $ref: '#/components/schemas/Tag'

    Post:
      description: 讨论版的帖子
      type: object
      required:
        - id
        - author
        - content
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
          maxLength: 5000
          minLength: 1
        created_at:
          description: 创建日期，ISO格式 datetime
          type: string
        updated_at:
          description: 更新日期，ISO格式 datetime
          type: string

    PostBrief:
      description: 讨论版帖子的简介信息
      type: object
      required:
        - id
        - author
        - brief
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/User'
        brief:
          type: string
          maxLength: 100
        created_at:
          description: 创建日期，ISO格式 datetime
          type: string
        updated_at:
          description: 更新日期，ISO格式 datetime
          type: string

    PostIndex:
      description: 讨论版帖子索引
      type: object
      required:
        - page
        - size
        - total
        - items
      properties:
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/PostBrief'

    Reply:
      description: 讨论版帖子的回帖
      type: object
      required:
        - id
        - author
        - content
        - reply_to
      properties:
        id:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
          maxLength: 2000
        reply_to:
          type: integer
          format: int32

    ReplyIndex:
      description: 讨论版帖子回帖的索引，分页查看回帖列表
      type: object
      required:
        - total
        - page
        - size
        - items
      properties:
        total:
          type: integer
          format: int32
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/Reply'

servers:
  - url: 127.0.0.1/api
    variables: {}

paths:
  /article:
    get:
      summary: 取得文章索引
      description: 取得文章列表，通过query参数控制分页
      tags: [文章]
      parameters:
        - name: page
          in: query
          required: false
          description: 分页页数
          schema:
            type: integer
            format: int32
            default: 1
        - name: size
          in: query
          required: false
          description: 每页文章数量
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleIndex'

    post:
      summary: 创建一篇文章
      description: 创建一篇文章
      tags: [文章]
      responses:
        201:
          description: 创建成功返回 http 201，无内容

  /article/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: integer
          format: int32

    get:
      summary: 获取文章详情
      description: 获取文章的具体内容和相关信息
      tags: [文章]
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'

    patch:
      summary: 修改文章
      description: 修改文章内容和属性
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleModification'
      tags: [文章]
      responses:
        200:
          description: Modified

    delete:
      summary: 删除文章
      description: 删除文章，只有管理员和文章属主可以删除
      tags: [文章]
      responses:
        204:
          description: 已删除

  /article/{id}/comment:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32

    get:
      summary: 取得文章评论列表
      description: 取得文章评论列表，可以通过 query 中的参数控制分页
      operationId: sakura_village.api.comment.search
      tags: [文章]
      responses:
        200:
          description: 评论结构等待实现

    post:
      summary: 创建评论
      description: 创建一条文章评论
      operationId: sakura_village.api.comment.post
      tags: [文章]
      responses:
        201:
          description: 创建成功

  /article/{id}/comment/{comment_id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: comment_id
        in: path
        required: true
        schema:
          type: integer
          format: int32

    delete:
      summary: 删除评论
      description: 删除评论，管理员可用
      operationId: sakura_village.api.comment.delete
      tags: [文章]
      responses:
        200:
          description: 删除成功


  /post:
    get:
      summary: ''
      description: ''
      operationId: ''
      tags: [讨论]
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostIndex'

    post:
      summary: ''
      description: ''
      operationId: ''
      tags: [讨论]
      responses:
        201:
          description: ''

  '/post/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32

    get:
      summary: ''
      description: ''
      operationId: ''
      tags: [讨论]
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /post/{id}/reply:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32

    get:
      summary: ''
      description: ''
      operationId: sakura_village.api.reply.search
      tags: [讨论]
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reply'

    post:
      summary: ''
      description: ''
      operationId: sakura_village.api.reply.post
      tags: [讨论]
      responses:
        201:
          description: ''
